# Studio external app contract
__PROJECT=axios
__TYPE=static
__BUILD_OUTPUT_DIR=dist/axios

# URL
PUBLIC_URL=https://axios.buzzing.cc

# Keys
BUZZING_AWS_ACCESS_KEY_ID=
BUZZING_AWS_SECRET_ACCESS_KEY=
BUZZING_AWS_DEFAULT_REGION=
BUZZING_AWS_ENDPOINT=

# Mapped to feed's expected env vars
AWS_ACCESS_KEY_ID=${BUZZING_AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${BUZZING_AWS_SECRET_ACCESS_KEY}
AWS_DEFAULT_REGION=${BUZZING_AWS_DEFAULT_REGION}
AWS_ENDPOINT=${BUZZING_AWS_ENDPOINT}
